feat: support pool full status for solo
axiomesh/axiom pull request #55
Opened 2023-08-10 06:22 UTC by Karenlrx

feat: support remove invalid tx for solo

fix: remove batches whe checkpoint triggered

2023-08-10 06:37 UTC, zunkk approved these changes

2023-08-10 09:40 UTC, ywh254 requested changes

2023-08-10 09:40 UTC, ywh254 commented on config/order.toml
> +checkpoint_period = 10          # The checkpoint period (in blocks)
这个checkpoint period配置放到mempool是为什么啊     这个应该算共识模块的配置？

2023-08-11 02:29 UTC, ywh254 commented on config/order.toml
checkpoint这个回退到rbft的配置里面把

2023-08-11 03:34 UTC, wally0327 approved these changes

2023-08-11 03:37 UTC, merged