fix(ledger_panic): fix ledger concurrent write and read panic err
axiomesh/axiom pull request #57
Opened 2023-08-11 09:31 UTC by Yiheng-Liu

2023-08-11 09:43 UTC, zunkk approved these changes

2023-08-13 12:00 UTC, ywh254 requested changes

2023-08-13 12:02 UTC, Yiheng-Liu commented on internal/ledger/state_ledger.go
这个是目前的一个过渡方案，后期重构的时候会改一下，不然的话结构改动会有点大，和刘敬讨论过这个问题了当时，我当时也感觉暴露出来不是特别好，不过目前让链不要panic比较要紧，这个问题后面可以再重构

2023-08-13 12:07 UTC, ywh254 commented on internal/ledger/state_ledger.go
过渡方案也不要直接暴露把，在ledger里面提供一个函数包一下也可以，类似于stateLedger转换函数，在ledger包里面小写就可以访问了

2023-08-14 01:47 UTC, wally0327 approved these changes

2023-08-14 01:48 UTC, zunkk approved these changes

2023-08-14 01:49 UTC, ywh254 approved these changes

2023-08-14 01:50 UTC, merged