add node member manager
axiomesh/axiom pull request #59
Opened 2023-08-14 01:41 UTC by yzh-d

2023-08-15 03:26 UTC, ywh254 requested changes

2023-08-15 03:26 UTC, ywh254 commented on internal/executor/system/common/common.go
> +	NodeMemberContractAddr = "0x0000000000000000000000000000000000001003"
可以复用节点管理的合约，节点管理负责节点加入，节点退出，节点升级

2023-08-15 03:26 UTC, ywh254 commented on internal/executor/system/governance/node_manager.go
> +	NodeProposalGas = 1000
这个gas常量我改过了   用我上面的节点管理的gas常量就行了   可以去掉了

2023-08-15 03:26 UTC, ywh254 commented on internal/executor/system/governance/node_manager.go
> +type Node struct {
这个Node好像没用？

2023-08-15 03:26 UTC, ywh254 commented on internal/executor/system/governance/node_manager_test.go
> +	"encoding/json"
gofmt没有配置把？

2023-08-16 01:56 UTC, zunkk commented on internal/peermgr/swarm.go
> +	success, data := swarm.ledger.GetState(types.NewAddressByStr(common.NodeManagerContractAddr), []byte(common.NodeManagerContractAddr))
系统合约的状态读写封装成函数在系统合约那里？

2023-08-16 01:56 UTC, zunkk commented on internal/peermgr/swarm.go
> +	success, data := swarm.ledger.GetState(types.NewAddressByStr(common.NodeManagerContractAddr), []byte(common.NodeManagerContractAddr))
外部不应该关心怎么读和序列化等

2023-08-16 01:56 UTC, zunkk commented on internal/peermgr/swarm.go
> +	var IsExist = false
变量小写开头

2023-08-16 01:56 UTC, zunkk commented on internal/ledger/genesis/genesis.go
> +	lg.SetState(types.NewAddressByStr(common.NodeManagerContractAddr), []byte(common.NodeManagerContractAddr), c)
同下

2023-08-16 08:07 UTC, ywh254 approved these changes

2023-08-16 08:09 UTC, zunkk approved these changes

2023-08-16 08:09 UTC, merged